/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ecal.npb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(eCAL_pb_Content, eCAL_pb_Content, AUTO)


PB_BIND(eCAL_pb_Sample, eCAL_pb_Sample, 2)


PB_BIND(eCAL_pb_SampleList, eCAL_pb_SampleList, AUTO)





