/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "layer.npb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(eCAL_pb_LayerParUdpMC, eCAL_pb_LayerParUdpMC, AUTO)


PB_BIND(eCAL_pb_LayerParShm, eCAL_pb_LayerParShm, AUTO)


PB_BIND(eCAL_pb_LayerParTcp, eCAL_pb_LayerParTcp, AUTO)


PB_BIND(eCAL_pb_ConnnectionPar, eCAL_pb_ConnnectionPar, AUTO)


PB_BIND(eCAL_pb_TransportLayer, eCAL_pb_TransportLayer, AUTO)





