/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "logging.npb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(eCAL_pb_LogMessage, eCAL_pb_LogMessage, AUTO)


PB_BIND(eCAL_pb_LogMessageList, eCAL_pb_LogMessageList, AUTO)



