/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "service.npb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(eCAL_pb_ServiceHeader, eCAL_pb_ServiceHeader, AUTO)


PB_BIND(eCAL_pb_Request, eCAL_pb_Request, AUTO)


PB_BIND(eCAL_pb_Response, eCAL_pb_Response, AUTO)


PB_BIND(eCAL_pb_Method, eCAL_pb_Method, AUTO)


PB_BIND(eCAL_pb_Service, eCAL_pb_Service, AUTO)


PB_BIND(eCAL_pb_Client, eCAL_pb_Client, AUTO)





