@echo off

pushd %~dp0

if not exist "_build\complete" mkdir "_build\complete"
if not exist "_build\sdk" mkdir "_build\sdk"

set "CMAKE_PREFIX_PATH=C:/Qt/5.15.2/msvc2015_64"

REM pushd %~dp0
REM cd _build\sdk
REM cmake ../.. -G "Visual Studio 16 2019" -A x64 -T v140 ^
        REM -DHAS_HDF5=ON ^
        REM -DHAS_QT5=ON ^
        REM -DHAS_CURL=ON ^
        REM -DHAS_CAPNPROTO=OFF ^
        REM -DBUILD_DOCS=OFF ^
        REM -DBUILD_APPS=OFF ^
        REM -DBUILD_SAMPLES=OFF ^
        REM -DBUILD_TIME=ON ^
        REM -DBUILD_PY_BINDING=OFF ^
        REM -DBUILD_CSHARP_BINDING=OFF ^
        REM -DBUILD_ECAL_TESTS=OFF ^
        REM -DECAL_LAYER_ICEORYX=OFF ^
        REM -DECAL_INCLUDE_PY_SAMPLES=OFF ^
        REM -DECAL_INSTALL_SAMPLE_SOURCES=OFF ^
        REM -DECAL_JOIN_MULTICAST_TWICE=OFF ^
        REM -DECAL_NPCAP_SUPPORT=ON ^
        REM -DECAL_THIRDPARTY_BUILD_CMAKE_FUNCTIONS=ON ^
        REM -DECAL_THIRDPARTY_BUILD_PROTOBUF=ON ^
        REM -DECAL_THIRDPARTY_BUILD_SPDLOG=ON ^
        REM -DECAL_THIRDPARTY_BUILD_TINYXML2=ON ^
        REM -DECAL_THIRDPARTY_BUILD_FINEFTP=ON ^
        REM -DECAL_THIRDPARTY_BUILD_CURL=ON ^
        REM -DECAL_THIRDPARTY_BUILD_GTEST=ON ^
        REM -DECAL_THIRDPARTY_BUILD_HDF5=ON ^
        REM -DECAL_THIRDPARTY_BUILD_TCPUB=ON ^
        REM -DECAL_THIRDPARTY_BUILD_RECYCLE=ON ^
        REM -DBUILD_SHARED_LIBS=OFF ^
        REM -DCMAKE_BUILD_TYPE=Debug ^
        REM -DCPACK_PACK_WITH_INNOSETUP=OFF
REM popd 

pushd %~dp0
cd _build\complete
cmake ../.. -G "Visual Studio 16 2019" -A x64 -T v140 ^
        -DHAS_HDF5=ON ^
        -DHAS_QT5=ON ^
        -DHAS_CURL=ON ^
        -DHAS_CAPNPROTO=OFF ^
        -DBUILD_DOCS=ON ^
        -DBUILD_APPS=ON ^
        -DBUILD_SAMPLES=ON ^
        -DBUILD_TIME=ON ^
        -DBUILD_PY_BINDING=ON ^
        -DBUILD_CSHARP_BINDING=OFF ^
        -DBUILD_ECAL_TESTS=ON ^
        -DECAL_LAYER_ICEORYX=OFF ^
        -DECAL_INCLUDE_PY_SAMPLES=OFF ^
        -DECAL_INSTALL_SAMPLE_SOURCES=ON ^
        -DECAL_JOIN_MULTICAST_TWICE=OFF ^
        -DECAL_NPCAP_SUPPORT=ON ^
        -DECAL_THIRDPARTY_BUILD_CMAKE_FUNCTIONS=ON ^
        -DECAL_THIRDPARTY_BUILD_PROTOBUF=ON ^
        -DECAL_THIRDPARTY_BUILD_SPDLOG=ON ^
        -DECAL_THIRDPARTY_BUILD_TINYXML2=ON ^
        -DECAL_THIRDPARTY_BUILD_FINEFTP=ON ^
        -DECAL_THIRDPARTY_BUILD_CURL=ON ^
        -DECAL_THIRDPARTY_BUILD_GTEST=ON ^
        -DECAL_THIRDPARTY_BUILD_HDF5=ON ^
        -DECAL_THIRDPARTY_BUILD_TCPUB=ON ^
        -DECAL_THIRDPARTY_BUILD_RECYCLE=ON ^
        -DBUILD_SHARED_LIBS=OFF ^
        -DCMAKE_BUILD_TYPE=Release ^
        -DCPACK_PACK_WITH_INNOSETUP=ON
popd
		
popd

pause