@echo off

pushd %~dp0

if not exist "_build\minimal" mkdir "_build\minimal"

set "CMAKE_PREFIX_PATH=C:/Qt/6.6.1/msvc2019_64"

pushd %~dp0\_build\minimal
cmake ../.. -G "Visual Studio 17 2022" -A x64 -T v142 ^
        -DHAS_HDF5=OFF ^
        -DHAS_QT=ON ^
        -DHAS_CURL=OFF ^
        -DHAS_CAPNPROTO=OFF ^
        -DHAS_FTXUI=OFF ^
        -DBUILD_DOCS=OFF ^
        -DBUILD_APPS=ON ^
        -DBUILD_SAMPLES=OFF ^
        -DBUILD_TIME=OFF ^
        -DBUILD_PY_BINDING=OFF ^
        -DBUILD_CSHARP_BINDING=OFF ^
        -DBUILD_ECAL_TESTS=OFF ^
        -DECAL_LAYER_ICEORYX=OFF ^
        -DECAL_INCLUDE_PY_SAMPLES=OFF ^
        -DECAL_INSTALL_SAMPLE_SOURCES=OFF ^
        -DECAL_JOIN_MULTICAST_TWICE=OFF ^
        -DECAL_NPCAP_SUPPORT=OFF ^
        -DECAL_THIRDPARTY_BUILD_PROTOCFUNCTIONS=ON ^
        -DECAL_THIRDPARTY_BUILD_PROTOBUF=ON ^
        -DECAL_THIRDPARTY_BUILD_SPDLOG=ON ^
        -DECAL_THIRDPARTY_BUILD_TINYXML2=ON ^
        -DECAL_THIRDPARTY_BUILD_FINEFTP=OFF ^
        -DECAL_THIRDPARTY_BUILD_CURL=OFF ^
        -DECAL_THIRDPARTY_BUILD_GTEST=OFF ^
        -DECAL_THIRDPARTY_BUILD_HDF5=OFF ^
        -DECAL_THIRDPARTY_BUILD_RECYCLE=ON ^
        -DECAL_THIRDPARTY_BUILD_TCP_PUBSUB=ON ^
        -DECAL_THIRDPARTY_BUILD_QWT=ON ^
        -DBUILD_SHARED_LIBS=OFF ^
        -DCPACK_PACK_WITH_INNOSETUP=OFF
popd 

popd

pause