// Auto-generated by protoc-gen-pbftags. DO NOT EDIT.
// Source: ecal/core/pb/datatype.proto

#pragma once

#include <protozero/types.hpp>
#include <cstdint>

namespace eCAL { namespace pb { 
enum class DataTypeInformation : ::protozero::pbf_tag_type {
    optional_string_name = 1,
    optional_string_encoding = 2,
    optional_bytes_descriptor_information = 3
};

inline constexpr uint32_t operator+(DataTypeInformation e) {
    return static_cast<uint32_t>(e);
}

} } 
