// Auto-generated by protoc-gen-pbftags. DO NOT EDIT.
// Source: ecal/core/pb/host.proto

#pragma once

#include <protozero/types.hpp>
#include <cstdint>

namespace eCAL { namespace pb { 
enum class OSInfo : ::protozero::pbf_tag_type {
    optional_string_name = 1
};

inline constexpr uint32_t operator+(OSInfo e) {
    return static_cast<uint32_t>(e);
}

enum class Host : ::protozero::pbf_tag_type {
    optional_string_name = 1,
    optional_message_os = 2
};

inline constexpr uint32_t operator+(Host e) {
    return static_cast<uint32_t>(e);
}

} } 
