// Auto-generated by protoc-gen-pbftags. DO NOT EDIT.
// Source: ecal/core/pb/layer.proto

#pragma once

#include <protozero/types.hpp>
#include <cstdint>

namespace eCAL { namespace pb { 
enum class LayerParUdpMC : ::protozero::pbf_tag_type {
};

inline constexpr uint32_t operator+(LayerParUdpMC e) {
    return static_cast<uint32_t>(e);
}

enum class LayerParShm : ::protozero::pbf_tag_type {
    repeated_string_memory_file_list = 1
};

inline constexpr uint32_t operator+(LayerParShm e) {
    return static_cast<uint32_t>(e);
}

enum class LayerParTcp : ::protozero::pbf_tag_type {
    optional_int32_port = 1
};

inline constexpr uint32_t operator+(LayerParTcp e) {
    return static_cast<uint32_t>(e);
}

enum class ConnectionPar : ::protozero::pbf_tag_type {
    optional_message_layer_par_udpmc = 1,
    optional_message_layer_par_shm = 2,
    optional_message_layer_par_tcp = 4
};

inline constexpr uint32_t operator+(ConnectionPar e) {
    return static_cast<uint32_t>(e);
}

enum class TransportLayer : ::protozero::pbf_tag_type {
    optional_enum_type = 1,
    optional_int32_version = 2,
    optional_bool_enabled = 6,
    optional_bool_active = 3,
    optional_message_par_layer = 5
};

inline constexpr uint32_t operator+(TransportLayer e) {
    return static_cast<uint32_t>(e);
}

enum class eTransportLayerType : std::int32_t {
    tl_none = 0,
    tl_ecal_udp_mc = 1,
    tl_ecal_shm = 4,
    tl_ecal_tcp = 5,
    tl_all = 255
};

inline constexpr std::int32_t operator+(eTransportLayerType v) {
    return static_cast<std::int32_t>(v);
}

} } 
