// Auto-generated by protoc-gen-pbftags. DO NOT EDIT.
// Source: ecal/core/pb/logging.proto

#pragma once

#include <protozero/types.hpp>
#include <cstdint>

namespace eCAL { namespace pb { 
enum class LogMessage : ::protozero::pbf_tag_type {
    optional_int64_time = 1,
    optional_string_host_name = 2,
    optional_int32_process_id = 3,
    optional_string_process_name = 4,
    optional_string_unit_name = 5,
    optional_int32_level = 6,
    optional_string_content = 7
};

inline constexpr uint32_t operator+(LogMessage e) {
    return static_cast<uint32_t>(e);
}

enum class LogMessageList : ::protozero::pbf_tag_type {
    repeated_message_log_messages = 1
};

inline constexpr uint32_t operator+(LogMessageList e) {
    return static_cast<uint32_t>(e);
}

} } 
