// Auto-generated by protoc-gen-pbftags. DO NOT EDIT.
// Source: ecal/core/pb/monitoring.proto

#pragma once

#include <protozero/types.hpp>
#include <cstdint>

namespace eCAL { namespace pb { 
enum class Monitoring : ::protozero::pbf_tag_type {
    repeated_message_hosts = 1,
    repeated_message_processes = 2,
    repeated_message_services = 3,
    repeated_message_clients = 5,
    repeated_message_topics = 4
};

inline constexpr uint32_t operator+(Monitoring e) {
    return static_cast<uint32_t>(e);
}

} } 
