// Auto-generated by protoc-gen-pbftags. DO NOT EDIT.
// Source: ecal/core/pb/process.proto

#pragma once

#include <protozero/types.hpp>
#include <cstdint>

namespace eCAL { namespace pb { 
enum class ProcessState : ::protozero::pbf_tag_type {
    optional_enum_severity = 1,
    optional_enum_severity_level = 3,
    optional_string_info = 2
};

inline constexpr uint32_t operator+(ProcessState e) {
    return static_cast<uint32_t>(e);
}

enum class Process : ::protozero::pbf_tag_type {
    optional_int32_process_id = 3,
    optional_string_host_name = 2,
    optional_string_process_name = 4,
    optional_string_shm_transport_domain = 18,
    optional_string_unit_name = 5,
    optional_string_process_parameter = 6,
    optional_int32_component_init_state = 15,
    optional_string_component_init_info = 16,
    optional_string_ecal_runtime_version = 17,
    optional_string_config_file_path = 19,
    optional_string_time_sync_module_name = 14,
    optional_int32_registration_clock = 1,
    optional_message_state = 12,
    optional_enum_time_sync_state = 13
};

inline constexpr uint32_t operator+(Process e) {
    return static_cast<uint32_t>(e);
}

enum class eProcessSeverity : std::int32_t {
    proc_sev_unknown = 0,
    proc_sev_healthy = 1,
    proc_sev_warning = 2,
    proc_sev_critical = 3,
    proc_sev_failed = 4
};

inline constexpr std::int32_t operator+(eProcessSeverity v) {
    return static_cast<std::int32_t>(v);
}

enum class eProcessSeverityLevel : std::int32_t {
    proc_sev_level_unknown = 0,
    proc_sev_level1 = 1,
    proc_sev_level2 = 2,
    proc_sev_level3 = 3,
    proc_sev_level4 = 4,
    proc_sev_level5 = 5
};

inline constexpr std::int32_t operator+(eProcessSeverityLevel v) {
    return static_cast<std::int32_t>(v);
}

enum class eTimeSyncState : std::int32_t {
    tsync_none = 0,
    tsync_realtime = 1,
    tsync_replay = 2
};

inline constexpr std::int32_t operator+(eTimeSyncState v) {
    return static_cast<std::int32_t>(v);
}

} } 
