// Auto-generated by protoc-gen-pbftags. DO NOT EDIT.
// Source: ecal/core/pb/service.proto

#pragma once

#include <protozero/types.hpp>
#include <cstdint>

namespace eCAL { namespace pb { 
enum class ServiceHeader : ::protozero::pbf_tag_type {
    optional_string_host_name = 1,
    optional_string_service_name = 2,
    optional_string_service_id = 7,
    optional_string_method_name = 3,
    optional_string_error = 4,
    optional_int32_id = 5,
    optional_enum_state = 6
};

inline constexpr uint32_t operator+(ServiceHeader e) {
    return static_cast<uint32_t>(e);
}

enum class ServiceHeader_eCallState : std::int32_t {
    none = 0,
    executed = 1,
    failed = 2
};

inline constexpr std::int32_t operator+(ServiceHeader_eCallState v) {
    return static_cast<std::int32_t>(v);
}

enum class Request : ::protozero::pbf_tag_type {
    optional_message_header = 1,
    optional_bytes_request = 2
};

inline constexpr uint32_t operator+(Request e) {
    return static_cast<uint32_t>(e);
}

enum class Response : ::protozero::pbf_tag_type {
    optional_message_header = 1,
    optional_bytes_response = 2,
    optional_int64_ret_state = 3
};

inline constexpr uint32_t operator+(Response e) {
    return static_cast<uint32_t>(e);
}

enum class Method : ::protozero::pbf_tag_type {
    optional_string_method_name = 1,
    optional_string_req_type = 2,
    optional_bytes_req_desc = 5,
    optional_string_resp_type = 3,
    optional_bytes_resp_desc = 6,
    optional_message_request_datatype_information = 7,
    optional_message_response_datatype_information = 8,
    optional_int64_call_count = 4
};

inline constexpr uint32_t operator+(Method e) {
    return static_cast<uint32_t>(e);
}

enum class Service : ::protozero::pbf_tag_type {
    optional_string_service_id = 9,
    optional_int32_process_id = 5,
    optional_string_host_name = 2,
    optional_string_process_name = 3,
    optional_string_unit_name = 4,
    optional_string_service_name = 6,
    repeated_message_methods = 8,
    optional_uint32_version = 10,
    optional_uint32_tcp_port_v0 = 7,
    optional_uint32_tcp_port_v1 = 11,
    optional_int32_registration_clock = 1
};

inline constexpr uint32_t operator+(Service e) {
    return static_cast<uint32_t>(e);
}

enum class Client : ::protozero::pbf_tag_type {
    optional_string_service_id = 7,
    optional_int32_process_id = 5,
    optional_string_host_name = 2,
    optional_string_process_name = 3,
    optional_string_unit_name = 4,
    optional_string_service_name = 6,
    repeated_message_methods = 9,
    optional_uint32_version = 8,
    optional_int32_registration_clock = 1
};

inline constexpr uint32_t operator+(Client e) {
    return static_cast<uint32_t>(e);
}

} } 
