// Auto-generated by protoc-gen-pbftags. DO NOT EDIT.
// Source: ecal/core/pb/topic.proto

#pragma once

#include <protozero/types.hpp>
#include <cstdint>

namespace eCAL { namespace pb { 
enum class Statistics : ::protozero::pbf_tag_type {
    optional_uint64_count = 1,
    optional_double_latest = 2,
    optional_double_min = 3,
    optional_double_max = 4,
    optional_double_mean = 5,
    optional_double_variance = 6
};

inline constexpr uint32_t operator+(Statistics e) {
    return static_cast<uint32_t>(e);
}

enum class Topic : ::protozero::pbf_tag_type {
    optional_int32_registration_clock = 1,
    optional_string_host_name = 2,
    optional_string_shm_transport_domain = 28,
    optional_int32_process_id = 3,
    optional_string_process_name = 4,
    optional_string_unit_name = 5,
    optional_string_topic_id = 6,
    optional_string_topic_name = 7,
    optional_string_direction = 8,
    optional_message_datatype_information = 30,
    repeated_message_transport_layer = 12,
    optional_int32_topic_size = 13,
    optional_int32_connections_local = 16,
    optional_int32_connections_external = 17,
    optional_int32_message_drops = 18,
    optional_int64_data_id = 19,
    optional_int64_data_clock = 20,
    optional_int32_data_frequency = 21,
    optional_message_data_latency_us = 31
};

inline constexpr uint32_t operator+(Topic e) {
    return static_cast<uint32_t>(e);
}

} } 
