struct string_message_
{
  string              tid;         // unique topic id (internally)
  long long           id;          // topic user id (Publisher::SetID() for subscriber side filtering)
  long long           clock;       // topic clock
  long long           time;        // topic time stamp
  char                compressed;  // payload compression mode
  long long           size;        // uncompressed size
  unsigned long long  hash;        // unique hash for that sample
  sequence<char>      payload;     // octet stream
};
