/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "topic.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(eCAL_pb_DataTypeInformation, eCAL_pb_DataTypeInformation, AUTO)


PB_BIND(eCAL_pb_Topic, eCAL_pb_Topic, 2)


PB_BIND(eCAL_pb_Topic_AttrEntry, eCAL_pb_Topic_AttrEntry, AUTO)



