# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '6.0.0a1.dev132+g2fc5d28ec.d20240919'
__version_tuple__ = version_tuple = (6, 0, 0, 'dev132', 'g2fc5d28ec.d20240919')
