[project]
name = "ecal-docs"
requires-python = ">=3.8"
dependencies = [
  "sphinx",
  "sphinx-book-theme",
  "sphinx-tabs",
  "PyGithub",
  "autodoc",
  "semantic-version", 
  "exhale",
  "Jinja2",
  "sphinxcontrib-apidoc",
  "sphinxcontrib-youtube"
]
