# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: person.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'person.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import animal_pb2 as animal__pb2
import house_pb2 as house__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\x12\tpb.People\x1a\x0c\x61nimal.proto\x1a\x0bhouse.proto\"\xbb\x01\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12&\n\x05stype\x18\x03 \x01(\x0e\x32\x17.pb.People.Person.SType\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x1b\n\x03\x64og\x18\x05 \x01(\x0b\x32\x0e.pb.Animal.Dog\x12$\n\x05house\x18\x06 \x01(\x0b\x32\x15.pb.Environment.House\"\x1d\n\x05SType\x12\x08\n\x04MALE\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'person_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSON']._serialized_start=55
  _globals['_PERSON']._serialized_end=242
  _globals['_PERSON_STYPE']._serialized_start=213
  _globals['_PERSON_STYPE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
