name: Fat source archive

on:  
  push:

jobs:
  fat-source-archive:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules:  'recursive'
        fetch-depth: 0

    - name: Create clean eCAL directory
      shell: bash
      run: |
        mkdir "${{ runner.workspace }}/cleaned"
        rsync \
        --recursive \
        --delete \
        --delete-excluded \
        --exclude=".git" \
        --exclude="*.git" \
        --stats \
        $GITHUB_WORKSPACE/ \
        ${{ runner.workspace }}/cleaned/ecal/ \

    - name: Patch git-get-revision-information.cmake
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        export git_commit_date=$(git show -s --format=%ci)
        export git_version_complete=$(git describe --tags --dirty)
        IFS='.'
        read -a ecal_version_array <<< "${git_version_complete:1}"
        
        export ecal_version_major=${ecal_version_array[0]}
        export ecal_version_minor=${ecal_version_array[1]}
        
        # Remove -nightly or +nightly etc.
        IFS='-'
        read -a ecal_patch_array <<< "${ecal_version_array[2]}"
        IFS='+'
        read -a ecal_patch_array <<< "${ecal_patch_array[0]}"
        
        export ecal_version_patch="${ecal_patch_array[0]}"
        
        cd ${{ runner.workspace }}/cleaned/ecal/thirdparty/cmakefunctions/cmake_functions/git/
        echo "
        function (git_revision_information)
          set(GIT_REVISION_MAJOR ${ecal_version_major}   PARENT_SCOPE)    
          set(GIT_REVISION_MAYOR ${ecal_version_major}   PARENT_SCOPE)
          set(GIT_REVISION_MINOR ${ecal_version_minor}   PARENT_SCOPE)
          set(GIT_REVISION_PATCH ${ecal_version_patch}  PARENT_SCOPE)
          set(GIT_DESCRIBE_TAG   \"$git_version_complete\"      PARENT_SCOPE)
          set(GIT_REVISION_DATE  \"$git_commit_date\" PARENT_SCOPE)
          set(eCAL_BUILD_DATE    \"$git_commit_date\" PARENT_SCOPE)
        endfunction (git_revision_information)
        " > "git_revision_information.cmake"
        
    - name: Create fat archive
      working-directory: ${{ runner.workspace }}/cleaned/
      run: tar -czvf ${{ runner.workspace }}/cleaned/ecal-fat-source.tar.gz ecal
      shell: bash

    - name: Upload source
      uses: actions/upload-artifact@v4
      with:
        name: ecal-fat-source
        path: ${{ runner.workspace }}/cleaned/ecal-fat-source.tar.gz
